name: lcv_ui_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/icons/home/
    - assets/icons/bar/
    - assets/icons/commons/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
          weight: 900
          style: italic
      
flutter_gen:
  output: lib/gen/ 
  line_length: 80
